"""empty message

Revision ID: 7b5d859b76a1
Revises: 
Create Date: 2023-01-22 09:00:47.236218

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "7b5d859b76a1"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Clan",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("member_id", sa.BigInteger(), nullable=False),
        sa.Column("rank_id", sa.Integer(), nullable=False),
        sa.Column("killcount", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "PlayerBotConfirmation",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "ts",
            sa.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("player_id", sa.Integer(), nullable=False),
        sa.Column("label_id", sa.Integer(), nullable=False),
        sa.Column("bot", mysql.TINYINT(display_width=1), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "Unique_player_label_bot",
        "PlayerBotConfirmation",
        ["player_id", "label_id", "bot"],
        unique=True,
    )
    op.create_table(
        "playerHiscoreDataChanges",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("playerHiscoreDataID", sa.Integer(), nullable=False),
        sa.Column("old_player_id", sa.Integer(), nullable=False),
        sa.Column("new_player_id", sa.Integer(), nullable=False),
        sa.Column("old_total", sa.Integer(), nullable=False),
        sa.Column("new_total", sa.Integer(), nullable=False),
        sa.Column(
            "change_at",
            sa.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "sentToJagex",
        sa.Column("entry", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("entry"),
    )
    op.create_table(
        "playerReports",
        sa.Column("reporting_id", sa.Integer(), nullable=False),
        sa.Column("reported_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["reported_id"],
            ["Players.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reporting_id"],
            ["Players.id"],
        ),
        sa.PrimaryKeyConstraint("reporting_id", "reported_id"),
    )
    op.create_table(
        "playerReportsManual",
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column("reporting_id", sa.Integer(), nullable=False),
        sa.Column("reported_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["reported_id"],
            ["Players.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reporting_id"],
            ["Players.id"],
        ),
        sa.PrimaryKeyConstraint("reporting_id", "reported_id"),
    )
    op.drop_table("xx_stats")
    op.drop_table("labelsJagex")
    op.add_column(
        "playerHiscoreDataXPChange",
        sa.Column("tombs_of_amascut", sa.Integer(), nullable=True),
    )
    op.add_column(
        "playerHiscoreDataXPChange",
        sa.Column("tombs_of_amascut_expert", sa.Integer(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("playerHiscoreDataXPChange", "tombs_of_amascut_expert")
    op.drop_column("playerHiscoreDataXPChange", "tombs_of_amascut")
    op.create_table(
        "labelsJagex",
        sa.Column(
            "id",
            mysql.INTEGER(),
            server_default=sa.text("'0'"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("label", mysql.VARCHAR(length=50), nullable=False),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "xx_stats",
        sa.Column(
            "player_count",
            mysql.BIGINT(),
            server_default=sa.text("'0'"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "confirmed_ban",
            mysql.TINYINT(display_width=1),
            server_default=sa.text("'0'"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "confirmed_player",
            mysql.TINYINT(display_width=1),
            server_default=sa.text("'0'"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "created",
            mysql.DATETIME(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.drop_table("playerReportsManual")
    op.drop_table("playerReports")
    op.drop_table("sentToJagex")
    op.drop_table("playerHiscoreDataChanges")
    op.drop_index("Unique_player_label_bot", table_name="PlayerBotConfirmation")
    op.drop_table("PlayerBotConfirmation")
    op.drop_table("Clan")
    # ### end Alembic commands ###
