apiVersion: v1
kind: Service
metadata:
  name: bd-dev-api-service
spec:
  selector:
    app: bd-dev-api
  ports:
  - protocol: "TCP"
    port: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bd-dev-api
spec:
  selector:
    matchLabels:
      app: bd-dev-api
  replicas: 3
  template:
    metadata:
      name: bl-dev-api-app
      labels:
        app: bd-dev-api
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - bd-dev-api
              topologyKey: kubernetes.io/hostname
      volumes:
        - name: nfs-volume-exports
          nfs: 
            server: 51.68.207.197
            path: /cluster/exports
      containers:
      - name: bd-dev-api
        image: hub.osrsbotdetector.com/bot-detector/bd-api:latest
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "1500m"
            memory: "2000Mi"
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: nfs-volume-exports
          mountPath: /code/exports
        livenessProbe:
          exec:
            command:
              - curl
              - --fail
              - http://localhost:5000/
          failureThreshold: 3
          periodSeconds: 30
      imagePullSecrets:
      - name: regcred
