apiVersion: v1
kind: Service
metadata:
  name: bd-dev-api-service
spec:
  selector:
    app: bd-dev-api
  ports:
  - protocol: "TCP"
    port: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bd-dev-api
spec:
  selector:
    matchLabels:
      app: bd-dev-api
  replicas: 1
  template:
    metadata:
      name: bl-dev-api-app
      labels:
        app: bd-dev-api
    spec:
      volumes:
        - name: nfs-volume
          nfs: 
            server: 51.68.207.197
            path: /cluster/exports
      containers:
      - name: bd-dev-api
        image: hub.osrsbotdetector.com/bot-detector/bd-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: nfs-volume
          mountPath: /code/exports
      imagePullSecrets:
      - name: regcred