apiVersion: v1
kind: Service
metadata:
  name: bd-prod-api-service
spec:
  selector:
    app: bd-prod-api
  ports:
  - protocol: "TCP"
    port: 4000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bd-prod-api
spec:
  selector:
    matchLabels:
      app: bd-prod-api
  replicas: 5
  template:
    metadata:
      name: bl-prod-api-app
      labels:
        app: bd-prod-api
    spec:
      volumes:
        - name: nfs-volume-exports
          nfs: 
            server: 51.68.207.197
            path: /cluster/exports
        - name: nfs-volume-logs
          nfs: 
            server: 51.68.207.197
            path: /cluster/logs
      containers:
      - name: bd-prod-api
        image: hub.osrsbotdetector.com/bot-detector/bd-api:production
        imagePullPolicy: Always
        ports:
        - containerPort: 4000
        volumeMounts:
        - name: nfs-volume-exports
          mountPath: /home/exports
        - name: nfs-volume-exports
          mountPath: /home/logs
      imagePullSecrets:
      - name: regcred