version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
      args:
        root_path: /
        api_port: 5000
    command: uvicorn api.app:app --host 0.0.0.0 --reload --reload-include api/*
    container_name: bd-dev-api
    env_file:
      - .env
    volumes:
      - '../Bot-Detector-Core-Files/api:/project/api'
    ports:
      - 5000:5000
    networks:
      - botdetector-network

networks:
  botdetector-network:
