apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: prod-api-hpa
spec:
  maxReplicas: 2 # define max replica count
  minReplicas: 1 # define min replica count
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bd-prod-api
  targetCPUUtilizationPercentage: 80 # target CPU utilization
