name: Deployment workflow
on:
  push:
    branches: [ main ]

jobs:
  checkout:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

  deploy:
    runs-on: self-hosted
    needs: [checkout]
    steps:
      - name: Docker
        run: |
          printf "${{ secrets.DB_URI }}" > ~/.env
          docker stop bot_detector
          pip3 install waitress
          docker-compose --verbose down
          docker-compose --verbose build --no-cache
          docker-compose --verbose up -d
          
