name: Deployment workflow
on:
  push:
    branches: [ main ]

jobs:
  checkout:
    runs-on: [self-hosted, node1, node2, node3]
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: |
        sudo systemctl stop flaskapi.service
        rm -rf error.log
        python3 -m pip install --upgrade pip
        (test -d env && rm -rf env || python3 -m venv env)
        source ./env/bin/activate
        pip3 install flake8 pytest
        if [ -f requirements.txt ]; then pip3 install -r requirements.txt; fi
  deploy:
    runs-on: self-hosted
    needs: [checkout]
    steps:
      - name: setup_env_Vars
        run: |
          echo "${{ secrets.DB_URI }}" > .env
          echo "${{ secrets.HTTP_PROXY }}" >> .env
          echo "${{ secrets.HTTPS_PROXY }}" >> .env
          echo "${{ secrets.DISCORD_SQL_URI }}" >> .env
          echo "${{ secrets.FLASK_PORT }}" >> .env
          echo dev_mode=0 >> .env
          
      - name: Start Flask API
        run: |
          sudo systemctl start flaskapi.service
