name: Production workflow
on:
  push:
    branches: [ main ]

jobs:
  setup:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Set Up ENV
      run: |
          echo "${{ secrets.ASYNCMY_URI }}" > .env
          echo "${{ secrets.HTTP_PROXY }}" >> .env
          echo "${{ secrets.HTTPS_PROXY }}" >> .env
          echo "${{ secrets.DISCORD_ASYNCMY_URI }}" >> .env
          echo "${{ secrets.FLASK_PORT }}" >> .env
          echo "${{ secrets.GRAVEYARD_WEBHOOK }}" >> .env
          echo "${{ secrets.FEEDBACK_WEBHOOK_URL }}" >> .env
          echo dev_mode=0 >> .env

  build-image:
    needs: setup
    runs-on: self-hosted
    steps:
    - name: Build the Docker image
      run: docker build . --file Dockerfile --build-arg api_port=4000 --build-arg root_path=/api -t bot-detector/bd-api:production

    - name: Tag Image
      run: docker tag bot-detector/bd-api:production hub.osrsbotdetector.com/bot-detector/bd-api:production
      
    - name: Login to Docker Registry
      run: echo "${{ secrets.DOCKER_REGISTRY_PASSWORD }}" | docker login https://hub.osrsbotdetector.com -u "${{ secrets.DOCKER_REGISTRY_USERNAME }}" --password-stdin

    - name: Push Image to Registry
      run: docker push hub.osrsbotdetector.com/bot-detector/bd-api:production

  deploy:
    needs: build-image
    runs-on: self-hosted
    steps:
    - name: Apply Possible Deployment Changes
      run: kubectl apply -f deployment/prod/

    - name: Restart Deployment for Possible Container Changes
      run: kubectl rollout restart deploy bd-prod-api