name: Test

on:
  push:
    branches:
      - main
  pull_request:
concurrency: test-${{ github.sha }}

jobs:
  test:
    runs-on: self-hosted

    env:
      PYTHON_VERSION: "3.10"

    steps:
      - name: Checks out repository
        uses: actions/checkout@v3

      - name: Check out mysql repository
        uses: actions/checkout@v3
        with:
          repository: Bot-detector/bot-detector-mysql
          path: bot-detector-mysql

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest anyio
          if [ -f dev-requirements.txt ]; then pip install -r dev-requirements.txt; fi
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Setup database container
        run: docker-compose up

      - name: Run tests
        run: |
          pytest tests
