name: test workflow
on:
  pull_request:
  push:
    branches: [main, develop]

jobs:
  setup:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Set Up ENV
        run: |
          echo "${{ secrets.ASYNCMY_URI }}" > .env
          echo "${{ secrets.DISCORD_ASYNCMY_URI }}" >> .env

  run-tests:
    runs-on: self-hosted
    needs: setup
    env:
      PYTHON_VERSION: "3.10"

    steps:
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest tests
